--- #YAML:1.0
name:               Inline-Wrapper
version:            0.05
abstract:           Convenient module wrapper/loader routines for Inline.pm
author:
    - Jason McManus (INFIDEL) <infidel@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:  0
    Inline:      0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
